### ISSUE TITLE
lib-face can't handle queries that include spaces

### ISSUE THREAD

**Issue by simonw** [duckduckgo/cpp-libface#7]
I've been experimenting with lib-face. I imported a set of data that included terms containing spaces, for example:

```
14  API Design  api-design
3   API Security    api-security
```

Running queries for "api%20des" or "api+des" do not return any results:

http://localhost:6767/face/suggest/?n=10&q=api%20des
http://localhost:6767/face/suggest/?n=10&q=api+des

Is this intended behaviour? The example in the quick-start guide includes terms that have spaces in them: https://github.com/duckduckgo/cpp-libface/wiki/Quick-Start-Guide

**Comment by dhruvbird** [comment]
Sorry about the late response. This was fixed a while ago by commit 9a2881bd9cfc704144c763bad82f11b95b852b66

Please do re-open if this is not fixed for you.

**Comment by dhruvbird** [comment]
And this commit too a35cfcea90989e8c0c23fc05e0960e794a099bc8.

**Comment by ghost** [comment]
This issue doesn't seem to be fixed. My query url is: "http://www.example.com/autocomplete/?q=rules+to+old+maid" and it returns no results. I'll reopen another issue for this

**Comment by dhruvbird** [comment]
@kristen1980 The right way to query would be: rules%20to%20old%20maid (and not +)

**Comment by ghost** [comment]
Ok. We are using this with JQuery autocomplete and the URLs are sent with "+" to nginx (the same way DDG appears to be sending them). We have nginx. How do we convert the "+" to "%20"?

**Comment by ghost** [comment]
I've tried a rewrite rule but it still doesn't return results for anything with spaces:

location ~ ^/lib/ {
      rewrite ^(._)+(._)$ $1%20$2;
      proxy_pass http://127.0.0.1:6457/face/suggest/$is_args$args;
    }

**Comment by ghost** [comment]
I've been looking at the code & I have no idea what needs to be changed since I don't know C++.

I am currently escaping the '+' in python since I couldn't figure it out in nginx. This makes the response time twice as long, since the customer is directed to our python app then redirected to nginx. Even if there is a solution in nginx I think the better way would be to handle the "+" in cpp-libface. In ajax that is the way they handle spaces rather than %20.
